spring.datasource.url=jdbc:h2:mem:pillboxdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password

# 2. JPA / Hibernate Settings
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# 3. H2 Console Settings
spring.h2.console.enabled=true
spring.h2.console.path=/h2