# MySQL Connection Settings
spring.datasource.url=jdbc:mysql://localhost:3306/pillboxdb?allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=root
# 99% of users need a password here. If yours is really empty, leave it blank.
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate Settings
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true